[book]
authors = ["backendcloud"]
language = "en"
multilingual = false
src = "src"
title = "client-go源码分析"

[output.html]
additional-css = ["style.css"]
additional-js = ["sidebar.js"]


# [output.pdf]